import 'dart:io';
import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/company_profile.dart';
import '../models/customer.dart';
import '../models/enums.dart';
import '../models/job.dart';
import '../models/job_note.dart';
import '../models/job_photo.dart';
import '../models/material_item.dart';
import '../utils/date_formatters.dart';
import '../utils/money_formatters.dart';

class PdfReportService {
  Future<Uint8List> buildJobReport({
    required Job job,
    required Customer? customer,
    required CompanyProfile companyProfile,
    required List<JobPhoto> photos,
    List<JobNote> notes = const [],
    List<MaterialItem> materials = const [],
    ReportType reportType = ReportType.fullJob,
    ReportTemplate template = ReportTemplate.standard,
  }) async {
    final document = pw.Document(title: '${job.title} ${reportType.label}');
    final logo = await _loadLogo(companyProfile.logoPath);
    final reportPhotos = photos
        .where((photo) => photo.includeInReport)
        .toList();
    final photoWidgets = await _photoSections(reportPhotos);

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(36),
        theme: pw.ThemeData.withFont(
          base: pw.Font.helvetica(),
          bold: pw.Font.helveticaBold(),
        ),
        header: (context) => _header(
          companyProfile: companyProfile,
          logo: logo,
          reportType: reportType,
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by TradeProof',
              style: _smallText(PdfColors.grey700),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: _smallText(PdfColors.grey700),
            ),
          ],
        ),
        build: (context) => [
          _reportTitle(job, reportType),
          pw.SizedBox(height: 16),
          _detailGrid(job: job, customer: customer),
          if ((job.summary ?? '').trim().isNotEmpty) ...[
            pw.SizedBox(height: 18),
            _sectionTitle('Job Summary'),
            pw.Text(job.summary!.trim(), style: _bodyText()),
          ],
          pw.SizedBox(height: 20),
          _sectionTitle('Photo Log'),
          if (reportPhotos.isEmpty)
            _emptyBox('No report-visible photos have been added yet.')
          else
            ...photoWidgets,
          if (notes.any((note) => note.visibleOnReport)) ...[
            pw.SizedBox(height: 20),
            _sectionTitle('Report Notes'),
            ...notes
                .where((note) => note.visibleOnReport)
                .map((note) => pw.Bullet(text: note.body)),
          ],
          if (materials.any((item) => item.includeOnReport)) ...[
            pw.SizedBox(height: 20),
            _sectionTitle('Materials'),
            _materialsTable(
              materials.where((item) => item.includeOnReport).toList(),
            ),
          ],
          pw.SizedBox(height: 22),
          _disclaimer(companyProfile),
        ],
      ),
    );

    return document.save();
  }

  Future<pw.MemoryImage?> _loadLogo(String? logoPath) async {
    if (logoPath == null || logoPath.trim().isEmpty) {
      return null;
    }
    final file = File(logoPath);
    if (!await file.exists()) {
      return null;
    }
    try {
      return pw.MemoryImage(await file.readAsBytes());
    } catch (_) {
      return null;
    }
  }

  pw.Widget _header({
    required CompanyProfile companyProfile,
    required pw.MemoryImage? logo,
    required ReportType reportType,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 14),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          if (logo != null)
            pw.Container(
              width: 48,
              height: 48,
              margin: const pw.EdgeInsets.only(right: 12),
              child: pw.Image(logo, fit: pw.BoxFit.contain),
            )
          else
            pw.Container(
              width: 48,
              height: 48,
              margin: const pw.EdgeInsets.only(right: 12),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#1464F4'),
                borderRadius: pw.BorderRadius.circular(6),
              ),
              alignment: pw.Alignment.center,
              child: pw.Text(
                'TP',
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  companyProfile.companyName?.trim().isNotEmpty == true
                      ? companyProfile.companyName!.trim()
                      : 'TradeProof',
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 3),
                pw.Text(
                  [
                        companyProfile.phone,
                        companyProfile.email,
                        if (companyProfile.licenseNumber?.trim().isNotEmpty ==
                            true)
                          'License ${companyProfile.licenseNumber}',
                      ]
                      .where((value) => (value ?? '').trim().isNotEmpty)
                      .join(' | '),
                  style: _smallText(PdfColors.grey700),
                ),
              ],
            ),
          ),
          pw.Text(
            reportType.label,
            style: pw.TextStyle(
              color: PdfColor.fromHex('#1464F4'),
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _reportTitle(Job job, ReportType reportType) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          job.title,
          style: pw.TextStyle(fontSize: 25, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          '${reportType.label} | ${DateFormatters.shortDateTime.format(DateTime.now())}',
          style: _bodyText(PdfColors.grey700),
        ),
      ],
    );
  }

  pw.Widget _detailGrid({required Job job, required Customer? customer}) {
    final rows = <List<String>>[
      ['Job date', DateFormatters.shortDate.format(job.jobDate)],
      ['Trade', job.tradeType.label],
      ['Status', job.status.label],
      if ((job.workOrderNumber ?? '').trim().isNotEmpty)
        ['Work order', job.workOrderNumber!.trim()],
      if ((job.technicianName ?? '').trim().isNotEmpty)
        ['Technician', job.technicianName!.trim()],
      if (customer != null) ['Customer', customer.name],
      if ((customer?.phone ?? '').trim().isNotEmpty)
        ['Customer phone', customer!.phone!.trim()],
      if ((customer?.email ?? '').trim().isNotEmpty)
        ['Customer email', customer!.email!.trim()],
      if ((customer?.address ?? '').trim().isNotEmpty)
        ['Jobsite', customer!.address!.trim()],
    ];

    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Wrap(
        spacing: 16,
        runSpacing: 10,
        children: rows
            .map(
              (row) => pw.SizedBox(
                width: 230,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      row.first.toUpperCase(),
                      style: pw.TextStyle(
                        color: PdfColors.grey600,
                        fontSize: 8,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 2),
                    pw.Text(row.last, style: _bodyText()),
                  ],
                ),
              ),
            )
            .toList(),
      ),
    );
  }

  Future<List<pw.Widget>> _photoSections(List<JobPhoto> photos) async {
    final byCategory = <PhotoCategory, List<JobPhoto>>{};
    for (final photo in photos) {
      byCategory.putIfAbsent(photo.category, () => []).add(photo);
    }

    final widgets = <pw.Widget>[];
    for (final entry in byCategory.entries) {
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(top: 12, bottom: 6),
          child: pw.Text(
            entry.key.label,
            style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
          ),
        ),
      );
      widgets.add(
        pw.Wrap(
          spacing: 12,
          runSpacing: 12,
          children: [for (final photo in entry.value) await _photoTile(photo)],
        ),
      );
    }
    return widgets;
  }

  Future<pw.Widget> _photoTile(JobPhoto photo) async {
    final file = File(photo.displayPath);
    pw.Widget image;
    if (await file.exists()) {
      try {
        image = pw.Image(
          pw.MemoryImage(await file.readAsBytes()),
          fit: pw.BoxFit.cover,
        );
      } catch (_) {
        image = _missingPhotoBox('Unsupported image format');
      }
    } else {
      image = _missingPhotoBox('Photo file missing');
    }

    return pw.Container(
      width: 240,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(width: 240, height: 150, child: image),
          pw.Padding(
            padding: const pw.EdgeInsets.all(8),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  DateFormatters.shortDateTime.format(photo.capturedAt),
                  style: _smallText(PdfColors.grey700),
                ),
                if ((photo.caption ?? '').trim().isNotEmpty) ...[
                  pw.SizedBox(height: 4),
                  pw.Text(photo.caption!.trim(), style: _bodyText()),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _materialsTable(List<MaterialItem> materials) {
    return pw.TableHelper.fromTextArray(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
      cellStyle: _bodyText(),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerRight,
        2: pw.Alignment.centerLeft,
        3: pw.Alignment.centerRight,
      },
      headers: const ['Material', 'Qty', 'Unit', 'Cost'],
      data: materials
          .map(
            (item) => [
              item.name,
              item.quantity.toStringAsFixed(
                item.quantity.truncateToDouble() == item.quantity ? 0 : 2,
              ),
              item.unit,
              item.totalCost == null
                  ? ''
                  : MoneyFormatters.usd.format(item.totalCost),
            ],
          )
          .toList(),
    );
  }

  pw.Widget _disclaimer(CompanyProfile profile) {
    final text = profile.defaultDisclaimer?.trim();
    if (text == null || text.isEmpty) {
      return pw.SizedBox.shrink();
    }
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Text(text, style: _smallText(PdfColors.grey700)),
    );
  }

  pw.Widget _sectionTitle(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(
        text,
        style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
      ),
    );
  }

  pw.Widget _emptyBox(String text) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Text(text, style: _bodyText(PdfColors.grey700)),
    );
  }

  pw.Widget _missingPhotoBox(String message) {
    return pw.Container(
      color: PdfColors.grey200,
      alignment: pw.Alignment.center,
      child: pw.Text(message, style: _smallText(PdfColors.grey700)),
    );
  }

  pw.TextStyle _bodyText([PdfColor? color]) {
    return pw.TextStyle(fontSize: 10.5, color: color ?? PdfColors.black);
  }

  pw.TextStyle _smallText([PdfColor? color]) {
    return pw.TextStyle(fontSize: 8.5, color: color ?? PdfColors.grey700);
  }
}
